spring.application.name=vacation-planner-backend
spring.datasource.username=admin
spring.datasource.password=parola
spring.datasource.url=jdbc:postgresql://localhost:5432/vacation-planner-db
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.flyway.enabled=true
spring.flyway.user=admin
spring.flyway.password=parola
spring.flyway.locations=classpath:db/migration
spring.flyway.url=jdbc:postgresql://localhost:5432/vacation-planner-db
