name: CI

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: vacation-planner-backend

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Set up JDK 25 (Temurin)
        uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: '25'

      - name: Cache Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Run tests
        run: ./gradlew check


      - name: Upload test reports
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: test-reports
          path: |
            vacation-planner-backend/build/reports/tests/test/
            vacation-planner-backend/build/test-results/test/
